
ADD puppet/hiera/common-test.json /etc/puppet/hieradata/common.json

# Run Puppet apply
RUN puppet apply --modulepath=/etc/puppet/modules/ --hiera_config /etc/puppet/hiera.yaml

WORKDIR /var/node/membercenter

# Copy Gemfile
ADD Gemfile Gemfile
ADD Rakefile Rakefile
ADD spec spec
ADD .rspec .rspec

# Install bundler and required Gems
RUN gem install bundler
RUN bundle
