
ADD puppet/hiera/common-test.json /etc/puppet/hieradata/common.json

# Run Puppet apply
RUN puppet apply --modulepath=/etc/puppet/modules/ --hiera_config /etc/puppet/hiera.yaml

WORKDIR /var/node/membercenter

# Copy Gemfile and spec
COPY Gemfile Gemfile
COPY Rakefile Rakefile
COPY spec spec
COPY .rspec .rspec

# Install bundler and required Gems
RUN gem install bundler
RUN bundle
